config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts, shallow: true do
    resources :comments
      resources :likes
    end
  
  

  root to: "posts#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

	has_many :comments
	has_many :likes

	has_attached_file :image, :styles => { :medium => "500x500#", :thumb => "150x150#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
    @post = Post.find(params[:post_id])
    @post.comments.create(comment_param)
  	redirect_to "/posts/#{@post.id}"
  	
  end

  def comment_param
  	params.require(:comment).permit(:comment)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@post.likes.create
		render json: {new_like_count: @post.likes.count}
	end 



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!, :except => [:index, :show]

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		Post.create(post_params)
		redirect_to '/posts'
	end

	def show
		@post = Post.find(params[:id])
	end

	def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = 'Post deleted successfully'
    redirect_to '/posts'
  end

	def post_params
		params.require(:post).permit(:title, :image)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">
        <div class="row">
            <header class="twelve columns">
                <a class="logo" href="/posts"><h1>Instagram</h1></a> 
									<section class="user-login">
										<% if user_signed_in? %>
											<%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "button"%>
										<% else %>
											<%= link_to "Sign in", new_user_session_path %>
											<%= link_to "Sign up", new_user_registration_path %>
										<% end %>
									</section>
         </header>
  

<a href='posts/new'>Add a post</a>

 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>

<%= yield %>

	</div>
</div>

</body>
</html>

app/views/posts/index.html.erb
<div class="row">
<% if @posts.any? %>
    <% @posts.reverse.each do |post| %>
  <div class="medium-3 columns"><%= link_to (image_tag post.image.url(:thumb)), post_path(post), id: "img-#{post.id}" %>
        <h2><%= link_to "#{post.title}", post_path(post) %></h2>
        <div><%= link_to "Delete Post", post_path(post), method: :delete %></div>
        </div>
             <% end %>
  <% else %>
  <div>No posts yet!</div>
      </div>
  
<% end %>

app/views/posts/new.html.erb
<h2>Add a photo:<h2>

<%= form_for Post.new, html: {multipart: true} do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %><h2>


<%= image_tag @post.image.url(:medium)%>

<p>
<%= link_to "Like", post_likes_path(@post), class: 'post-like' %>
<span class="like_count"><%= @post.likes.count %></span> likes

</p>




<a href="#" class="comment-form">Post A Comment</a>

<section class="comments">
<%= form_for [@post, Comment.new] do |f| %>
  <%= f.label :comment %>
  <%= f.text_area :comment, class: "comment" %>
  <%= f.submit 'Post Comment', class: "post-comment" %>
<% end %>
</section>

<ul>
    <% @post.comments.each do |comment| %>
      <li><%= comment.comment %></li>
    <% end %>
  </ul>